### PR TITLE
Build with Visual Studio

### PR DESCRIPTION
**Pull request by exelix11**
This allows to build the Windows version directly with Visual Studio, tested on my main pc with vs2019, in theory it doesn't use any feature that wouldn't work on earlier versions but haven't tried.

### CODE REVIEW

**Comment by fincs** [comment]
[meson is able to generate Visual Studio solutions](https://mesonbuild.com/Using-with-Visual-Studio.html), although I haven't tested it since on Windows I build cross platform code exclusively with msys2's mingw64 compiler. Can you test this? I would prefer to avoid having multiple PC platform specific build systems.

**Comment by exelix11** [comment]
I know but i don't use meson on my main pc, so I figured out some other people may find the prebuilt sln useful

**Comment by fincs** [comment]
Like I said, I would prefer to avoid having multiple PC build systems. Having a separate VS-based build system that is independent of the main PC one makes it harder to maintain a project based on this template, while meson is already supposed to be capable of automatically generating VS files.

**Comment by exelix11** [comment]
No problem then 👍

**Pull request closed without merging**
